### ISSUE TITLE
Typo in Graphic

### ISSUE THREAD

**Issue by RylanBauermeister** [learn-co-curriculum/fewpjs_the_dom_tree#1]
The graphic being used to depict a DOM tree has attribute misspelled.  I find this distressing.

**Comment by jenmyers** [comment]
Thanks for bringing this to our attention! We recently gained some design support so that we can better illustrate lesson concepts. I've added this to our design request queue and I'll update when completed.

**Comment by RylanBauermeister** [comment]
Yay!  Thanks!

**Comment by sgharms** [comment]
Updated!
